### PR TITLE
Add minItems to be at least 1 to arrays

### PR DESCRIPTION
**Pull request by jonnyshaw89**
Require schemas to provide at least 1 entry for each defined array

### CODE REVIEW

**Comment by jonnyshaw89** [comment]
This is ready to review but currently breaks some of our test schemas.
Ill raise a PR in runner to make the schemas valid

**Comment by SamGodwin2** [comment]
[Summary page not working when previewing survey](https://trello.com/c/MdsQQznU/507-summary-page-not-working-when-previewing-survey)

**Comment by samiwel** [comment]
In addition to fixing the test schemas is survey runner, is it worth creating a test schema in this repo and asserting any empty arrays fail JSON schema validation?

**Comment by jonnyshaw89** [comment]
https://github.com/ONSdigital/eq-survey-runner/pull/1675 needs merging at the same time

**Pull request merged**
