### PR TITLE
Remove references to session prompts

### PR DESCRIPTION
**Pull request by adammahmood**
### What is the context of this PR?
Removes references to session prompts which have been removed from `eq-survey-runner` as per https://github.com/ONSdigital/eq-survey-runner/pull/1964

### How to review 
- Ensure tests pass

### CODE REVIEW

**Comment by adammahmood** [comment]
[Remove session timeout javascript from runner](https://trello.com/c/dm6AG2Mu/808-remove-session-timeout-javascript-from-runner)

**Comment by jonnyshaw89** [comment]
Set these 2 lines
https://github.com/ONSdigital/eq-survey-runner/blob/master/scripts/test_schemas.sh#L10
to include your branch name to test the schemas on build with this validator
`onsdigital/eq-schema-validator:808-remove-session-timeout-javascript-from-runner`

**Comment by adammahmood** [comment]
> Set these 2 lines
> https://github.com/ONSdigital/eq-survey-runner/blob/master/scripts/test_schemas.sh#L10
> to include your branch name to test the schemas on build with this validator
> `onsdigital/eq-schema-validator:808-remove-session-timeout-javascript-from-runner`

All tests pass when running `pipenv run ./scripts/test_schemas.sh` with `onsdigital/eq-schema-validator:808-remove-session-timeout-javascript-from-runner`

**Comment by jonnyshaw89** [comment]
Merging this will cause the runner build to fail until https://github.com/ONSdigital/eq-survey-runner/pull/1964/files#diff-d1807900ec999098c60f0eb151ed0112L7 is merged

**Pull request merged**
